name: auto_injector
description: Automatic Dependency Injection System, but without build_runner :)
version: 1.2.0
repository: https://github.com/Flutterando/auto_injector

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fake_reflection: ">=1.0.2 <2.0.0"
  meta: ">=1.5.0 <2.0.0"
  uuid: ^3.0.7

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.16.0
